apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_image
        imagePullPolicy: Never
        ports:
          - name: wpport
            containerPort: 5050
        livenessProbe:
          exec:
            command:
              - sh
              - health.sh
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress
  ports:
  - name: wpport
    protocol: TCP
    port: 5050
    targetPort: 5050
  type: LoadBalancer

